[package]
name = "counter"
version = "0.1.0"
authors = ["dev <dev@matrixport.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
athena_rust_api = { path = "../../../athena-rust-api", version = "0.0.1" }